name: tiktok
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.18.4 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  cached_network_image: ^3.2.3
  cloud_firestore: ^4.1.0
  firebase_auth: ^4.1.3
  firebase_core: ^2.3.0
  firebase_storage: ^11.0.6
  image_picker: ^0.8.6
  timeago: ^3.3.0
  video_compress: ^3.1.1
  video_player: ^2.4.7

dev_dependencies: 
  flutter_lints: ^2.0.0
  lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

